package com.bzsoft.wjdbc.command;

import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectOutput;
import java.sql.SQLException;
import java.sql.Statement;

public class StatementExecuteExtendedCommand implements Command<Boolean, Statement> {

	private static final long	serialVersionUID	= 3978992080531764787L;

	private String					sql;
	private int						autoGeneratedKeys;
	private int[]					columnIndexes;
	private String[]				columnNames;

	public StatementExecuteExtendedCommand() {
		// empty
	}

	public StatementExecuteExtendedCommand(final String sql, final int autoGeneratedKeys) {
		this.sql = sql;
		this.autoGeneratedKeys = autoGeneratedKeys;
	}

	public StatementExecuteExtendedCommand(final String sql, final int[] columnIndexes) {
		this.sql = sql;
		this.columnIndexes = columnIndexes;
	}

	public StatementExecuteExtendedCommand(final String sql, final String[] columnNames) {
		this.sql = sql;
		this.columnNames = columnNames;
	}

	@Override
	public void writeExternal(final ObjectOutput out) throws IOException {
		out.writeUTF(sql);
		out.writeInt(autoGeneratedKeys);
		out.writeObject(columnIndexes);
		out.writeObject(columnNames);
	}

	@Override
	public void readExternal(final ObjectInput in) throws IOException, ClassNotFoundException {
		this.sql = in.readUTF();
		this.autoGeneratedKeys = in.readInt();
		this.columnIndexes = (int[]) in.readObject();
		this.columnNames = (String[]) in.readObject();
	}

	@Override
	public Boolean execute(final Statement target, final ConnectionContext ctx) throws SQLException {
		final String sentence = ctx.resolveOrCheckQuery(this.sql);
		// Now make the descision what call to execute
		if (columnIndexes != null) {
			return Boolean.valueOf(target.execute(sentence, columnIndexes));
		} else if (columnNames != null) {
			return Boolean.valueOf(target.execute(sentence, columnNames));
		} else {
			return Boolean.valueOf(target.execute(sentence, autoGeneratedKeys));
		}
	}

	@Override
	public String toString() {
		return "StatementUpdateExtendedCommand: " + sql;
	}
}
